### ISSUE TITLE
mp4split no longer available

### ISSUE THREAD

**Issue by sqlbloke** [javaguirre/unified-silex-example#1]
sorry to let you no I couldn't get it installed 

~$ sudo apt-get -y install mp4split
Reading package lists... Done
Building dependency tree  
Reading state information... Done
E: Unable to locate package mp4split

**Comment by javaguirre** [comment]
Hi @sqlbloke,

If it's not in your OS repository you could also install it manually: http://docs.unified-streaming.com/installation/advanced/mp4split.html#linux

What OS are you using and which version? Ubuntu? Debian?
